/*
 * Copyright The Zephyr Project Contributors
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/** @file
 * @brief UOTGHS to USBHS compatibility definitions for the SAM3X series.
 *
 * The SAM3X UOTGHS and the SAM E70/S70/V70/V71 USBHS are the same USB
 * controller. The device register block has identical offsets and identical
 * bitfield positions and encodings in both; only the macro prefix differs.
 * This header maps the UOTGHS names onto the USBHS names used by
 * udc_sam_usbhs.c and supplies the positional and shift helpers that the
 * older ASF UOTGHS header does not define.
 *
 * SAM3X specifics that are not a plain rename:
 *   - UOTGHS_CTRL_OTGPADE must be set to power the OTG pad, otherwise
 *     clearing UOTGHS_DEVCTRL_DETACH does not pull up D+.
 *   - UOTGHS_CTRL_UIDE must be clear for UOTGHS_CTRL_UIMOD to select device
 *     mode. It is set after reset, so UOTGHS_CTRL must be written as a whole
 *     word and never read-modify-written.
 *   - The USB_48M gate is PMC_SCER_UOTGCLK, not PMC_SCER_USBCLK.
 */

#ifndef ZEPHYR_DRIVERS_USB_UDC_UDC_SAM_UOTGHS_COMPAT_H_
#define ZEPHYR_DRIVERS_USB_UDC_UDC_SAM_UOTGHS_COMPAT_H_

/* Peripheral instance type */
#define Usbhs					Uotghs

/* General control and status */
#define USBHS_CTRL				UOTGHS_CTRL
#define USBHS_CTRL_FRZCLK			UOTGHS_CTRL_FRZCLK
#define USBHS_CTRL_UIMOD			UOTGHS_CTRL_UIMOD
#define USBHS_CTRL_USBE				UOTGHS_CTRL_USBE
#define USBHS_SR				UOTGHS_SR
#define USBHS_SR_CLKUSABLE			UOTGHS_SR_CLKUSABLE
#define USBHS_SR_SPEED_Msk			UOTGHS_SR_SPEED_Msk
#define USBHS_SR_SPEED_Pos			UOTGHS_SR_SPEED_Pos

/* Device general control */
#define USBHS_DEVCTRL				UOTGHS_DEVCTRL
#define USBHS_DEVCTRL_ADDEN			UOTGHS_DEVCTRL_ADDEN
#define USBHS_DEVCTRL_DETACH			UOTGHS_DEVCTRL_DETACH
#define USBHS_DEVCTRL_RMWKUP			UOTGHS_DEVCTRL_RMWKUP
#define USBHS_DEVCTRL_SPDCONF_FORCED_FS		UOTGHS_DEVCTRL_SPDCONF_FORCED_FS
#define USBHS_DEVCTRL_SPDCONF_HIGH_SPEED	UOTGHS_DEVCTRL_SPDCONF_HIGH_SPEED
#define USBHS_DEVCTRL_SPDCONF_Msk		UOTGHS_DEVCTRL_SPDCONF_Msk
#define USBHS_DEVCTRL_SPDCONF_NORMAL		UOTGHS_DEVCTRL_SPDCONF_NORMAL
#define USBHS_DEVCTRL_TSTJ			UOTGHS_DEVCTRL_TSTJ
#define USBHS_DEVCTRL_TSTK			UOTGHS_DEVCTRL_TSTK
#define USBHS_DEVCTRL_TSTPCKT			UOTGHS_DEVCTRL_TSTPCKT
#define USBHS_DEVCTRL_UADD			UOTGHS_DEVCTRL_UADD
#define USBHS_DEVCTRL_UADD_Msk			UOTGHS_DEVCTRL_UADD_Msk

/* Device global interrupt */
#define USBHS_DEVISR				UOTGHS_DEVISR
#define USBHS_DEVISR_EORSM			UOTGHS_DEVISR_EORSM
#define USBHS_DEVISR_EORST			UOTGHS_DEVISR_EORST
#define USBHS_DEVISR_PEP_0			UOTGHS_DEVISR_PEP_0
#define USBHS_DEVISR_SOF			UOTGHS_DEVISR_SOF
#define USBHS_DEVISR_SUSP			UOTGHS_DEVISR_SUSP
#define USBHS_DEVISR_WAKEUP			UOTGHS_DEVISR_WAKEUP
#define USBHS_DEVICR				UOTGHS_DEVICR
#define USBHS_DEVICR_EORSMC			UOTGHS_DEVICR_EORSMC
#define USBHS_DEVICR_EORSTC			UOTGHS_DEVICR_EORSTC
#define USBHS_DEVICR_SOFC			UOTGHS_DEVICR_SOFC
#define USBHS_DEVICR_SUSPC			UOTGHS_DEVICR_SUSPC
#define USBHS_DEVICR_WAKEUPC			UOTGHS_DEVICR_WAKEUPC
#define USBHS_DEVIMR				UOTGHS_DEVIMR
#define USBHS_DEVIDR				UOTGHS_DEVIDR
#define USBHS_DEVIDR_SUSPEC			UOTGHS_DEVIDR_SUSPEC
#define USBHS_DEVIDR_WAKEUPEC			UOTGHS_DEVIDR_WAKEUPEC
#define USBHS_DEVIER				UOTGHS_DEVIER
#define USBHS_DEVIER_EORSMES			UOTGHS_DEVIER_EORSMES
#define USBHS_DEVIER_EORSTES			UOTGHS_DEVIER_EORSTES
#define USBHS_DEVIER_SOFES			UOTGHS_DEVIER_SOFES
#define USBHS_DEVIER_SUSPES			UOTGHS_DEVIER_SUSPES
#define USBHS_DEVIER_WAKEUPES			UOTGHS_DEVIER_WAKEUPES

/* Endpoint enable and reset */
#define USBHS_DEVEPT				UOTGHS_DEVEPT
#define USBHS_DEVEPT_EPEN0			UOTGHS_DEVEPT_EPEN0
#define USBHS_DEVEPT_EPRST0			UOTGHS_DEVEPT_EPRST0

/* Endpoint configuration */
#define USBHS_DEVEPTCFG				UOTGHS_DEVEPTCFG
#define USBHS_DEVEPTCFG_ALLOC			UOTGHS_DEVEPTCFG_ALLOC
#define USBHS_DEVEPTCFG_AUTOSW			UOTGHS_DEVEPTCFG_AUTOSW
#define USBHS_DEVEPTCFG_EPDIR_IN		UOTGHS_DEVEPTCFG_EPDIR_IN

/* Endpoint status and interrupt */
#define USBHS_DEVEPTISR				UOTGHS_DEVEPTISR
#define USBHS_DEVEPTISR_BYCT_Msk		UOTGHS_DEVEPTISR_BYCT_Msk
#define USBHS_DEVEPTISR_BYCT_Pos		UOTGHS_DEVEPTISR_BYCT_Pos
#define USBHS_DEVEPTISR_CFGOK			UOTGHS_DEVEPTISR_CFGOK
#define USBHS_DEVEPTISR_DTSEQ_Msk		UOTGHS_DEVEPTISR_DTSEQ_Msk
#define USBHS_DEVEPTISR_DTSEQ_Pos		UOTGHS_DEVEPTISR_DTSEQ_Pos
#define USBHS_DEVEPTISR_NBUSYBK_Msk		UOTGHS_DEVEPTISR_NBUSYBK_Msk
#define USBHS_DEVEPTISR_NBUSYBK_Pos		UOTGHS_DEVEPTISR_NBUSYBK_Pos
#define USBHS_DEVEPTISR_RXOUTI			UOTGHS_DEVEPTISR_RXOUTI
#define USBHS_DEVEPTISR_RXSTPI			UOTGHS_DEVEPTISR_RXSTPI
#define USBHS_DEVEPTISR_TXINI			UOTGHS_DEVEPTISR_TXINI
#define USBHS_DEVEPTICR				UOTGHS_DEVEPTICR
#define USBHS_DEVEPTICR_RXOUTIC			UOTGHS_DEVEPTICR_RXOUTIC
#define USBHS_DEVEPTICR_RXSTPIC			UOTGHS_DEVEPTICR_RXSTPIC
#define USBHS_DEVEPTICR_TXINIC			UOTGHS_DEVEPTICR_TXINIC
#define USBHS_DEVEPTIMR				UOTGHS_DEVEPTIMR
#define USBHS_DEVEPTIMR_FIFOCON			UOTGHS_DEVEPTIMR_FIFOCON
#define USBHS_DEVEPTIMR_STALLRQ			UOTGHS_DEVEPTIMR_STALLRQ
#define USBHS_DEVEPTIER				UOTGHS_DEVEPTIER
#define USBHS_DEVEPTIER_RXOUTES			UOTGHS_DEVEPTIER_RXOUTES
#define USBHS_DEVEPTIER_RXSTPES			UOTGHS_DEVEPTIER_RXSTPES
#define USBHS_DEVEPTIER_STALLRQS		UOTGHS_DEVEPTIER_STALLRQS
#define USBHS_DEVEPTIER_TXINES			UOTGHS_DEVEPTIER_TXINES
#define USBHS_DEVEPTIDR				UOTGHS_DEVEPTIDR
#define USBHS_DEVEPTIDR_FIFOCONC		UOTGHS_DEVEPTIDR_FIFOCONC
#define USBHS_DEVEPTIDR_RXOUTEC			UOTGHS_DEVEPTIDR_RXOUTEC
#define USBHS_DEVEPTIDR_STALLRQC		UOTGHS_DEVEPTIDR_STALLRQC
#define USBHS_DEVEPTIDR_TXINEC			UOTGHS_DEVEPTIDR_TXINEC

/*
 * Positional definitions absent from the ASF UOTGHS header. Values taken from
 * the SAM3X datasheet register descriptions (UOTGHS_DEVEPT bits 8:0 EPENx and
 * 24:16 EPRSTx, UOTGHS_DEVISR bits 21:12 PEP_x).
 */
#define USBHS_DEVEPT_EPEN0_Pos			0
#define USBHS_DEVEPT_EPRST0_Pos			16
#define USBHS_DEVISR_PEP_0_Pos			12
#define USBHS_DEVIDR_PEP_0_Pos			12
#define USBHS_DEVIER_PEP_0_Pos			12
#define USBHS_DEVISR_PEP__Msk			(0x3ffu << USBHS_DEVISR_PEP_0_Pos)
#define USBHS_SR_SPEED_HIGH_SPEED_Val		1

/* Shift helpers absent from the ASF UOTGHS header */
#define USBHS_DEVEPTCFG_EPBK(value)					\
	(UOTGHS_DEVEPTCFG_EPBK_Msk &					\
	 ((value) << UOTGHS_DEVEPTCFG_EPBK_Pos))
#define USBHS_DEVEPTCFG_EPSIZE(value)					\
	(UOTGHS_DEVEPTCFG_EPSIZE_Msk &					\
	 ((value) << UOTGHS_DEVEPTCFG_EPSIZE_Pos))
#define USBHS_DEVEPTCFG_EPTYPE(value)					\
	(UOTGHS_DEVEPTCFG_EPTYPE_Msk &					\
	 ((value) << UOTGHS_DEVEPTCFG_EPTYPE_Pos))

/* The USB_48M clock gate is named after the OTG controller on SAM3X */
#define PMC_SCER_USBCLK				PMC_SCER_UOTGCLK
#define PMC_SCDR_USBCLK				PMC_SCDR_UOTGCLK

#endif /* ZEPHYR_DRIVERS_USB_UDC_UDC_SAM_UOTGHS_COMPAT_H_ */
