/*
 * Copyright (c) 2026 Eve Redero
 * SPDX-License-Identifier: Apache-2.0
 *
 * STM32 DAC audio output — implements audio_codec_api.
 *
 * Hardware: DAC CH1 triggered by a basic timer via DMAMUX/DMA.
 * The timer fires at the configured sample rate; each tick moves one 16-bit
 * sample from memory to the DAC DHR12R1 register.
 *
 * Application flow:
 *   audio_codec_configure()            — set sample rate, configure HW
 *   audio_codec_register_done_callback() — register TX-done callback
 *   audio_codec_write(dev, buf, size)  — prime first buffer into DMA
 *   audio_codec_start(dev, TX)         — enable DAC + timer
 *   [in callback] audio_codec_write()  — reload next buffer continuously
 *   audio_codec_stop(dev, TX)          — stop timer + DMA + DAC
 */

#define DT_DRV_COMPAT st_stm32_dac_audio

#include <zephyr/kernel.h>
#include <zephyr/device.h>
#include <zephyr/audio/codec.h>
#include <zephyr/drivers/dma.h>
#include <zephyr/drivers/dma/dma_stm32.h>
#include <zephyr/drivers/clock_control/stm32_clock_control.h>
#include <zephyr/drivers/clock_control.h>
#include <zephyr/drivers/pinctrl.h>
#include <zephyr/cache.h>
#include <zephyr/irq.h>
#include <zephyr/logging/log.h>
#include <soc.h>
#include <stm32_ll_dac.h>
#include <stm32_ll_tim.h>

LOG_MODULE_REGISTER(dac_audio_stm32, CONFIG_AUDIO_CODEC_LOG_LEVEL);

/*
 * Syntactic trigger-source lookup via DT_STRING_TOKEN.
 *
 * The st,trig-source DTS property (e.g. "TIM6") is converted to a bare
 * token by DT_STRING_TOKEN, then pasted to form LL_DAC_TRIG_EXT_TIM6_TRGO.
 * No address arithmetic, no ternary chain, no stubs. If the resulting
 * constant is undefined for the target SoC the build fails at the
 * .trig_source initialiser with an "undeclared identifier" error.
 *
 * Two-level expansion is required: the outer macro forces DT_STRING_TOKEN
 * to expand fully (to e.g. TIM6), then the inner ## pastes the token
 * directly without re-expanding it. This avoids the CMSIS definition
 * TIM6 = ((TIM_TypeDef *)TIM6_BASE) being substituted before the paste.
 */
/* The st,trig-source property holds the suffix of the LL constant after
 * the LL_DAC_TRIG_EXT_ prefix (e.g. "TIM6_TRGO").  Using the full suffix
 * avoids the CMSIS token TIM6, which is itself a macro expanding to a
 * cast expression that would break token-pasting if used as an operand.
 * _PASTE does the ## with t adjacent, so the DT token is not re-expanded. */
#define _STM32_DAC_TRIG_PASTE(t)  LL_DAC_TRIG_EXT_##t
#define _STM32_DAC_TRIG_EXPAND(t) _STM32_DAC_TRIG_PASTE(t)
#define STM32_DAC_TRIG_SOURCE(inst)					\
	_STM32_DAC_TRIG_EXPAND(						\
		DT_STRING_TOKEN(DT_DRV_INST(inst), st_trig_source))

struct dac_audio_cfg {
	DAC_TypeDef *dac;
	TIM_TypeDef *tim;
	uint32_t     trig_source;
	const struct device *dma_dev;
	uint32_t dma_channel;
	uint32_t dma_slot;
	const struct pinctrl_dev_config *pcfg;
	const struct stm32_pclken *pclken;
	size_t pclk_len;
	/* Timer clock source entry (clocks[1] of the timer node) used only
	 * with clock_control_get_rate() — already accounts for the APB×2
	 * multiplier so no manual factor is needed. */
	struct stm32_pclken tim_clksrc;
	/* IRQ connect+enable function — instance-specific, generated by macro */
	void (*irq_config)(void);
};

struct dac_audio_data {
	bool running;
	bool dma_configured;
	uint32_t dest_addr;
	struct dma_config dma_cfg;
	struct dma_block_config dma_block;
	audio_codec_tx_done_callback_t tx_cb;
	void *tx_cb_user_data;
	/* Pre-queued next buffer: set by write() while DMA is running so the
	 * reload happens at ISR time (before the user callback), eliminating
	 * the buffer-fill time from the inter-buffer gap. */
	uint8_t *next_buf;
	size_t   next_size;
	bool     next_valid;
#ifdef CONFIG_DAC_AUDIO_STM32_DOUBLE_BUFFER
	/* Internal double buffer for cyclic DMA.  DMA runs on dbl_buf[0..2N)
	 * continuously; write() copies into the idle half while the active
	 * half plays.  Cache-line aligned so partial flushes are safe. */
	uint16_t __aligned(32) dbl_buf[2 * CONFIG_DAC_AUDIO_STM32_MAX_BLOCK_SAMPLES];
	uint8_t  active_half; /* 0 or 1 — half currently being played by DMA */
	size_t   half_bytes;  /* bytes in one half = block size from first write() */
#endif
};

static void dma_tx_callback(const struct device *dma_dev, void *user_data,
			     uint32_t channel, int status)
{
	const struct device *dev = user_data;
	const struct dac_audio_cfg *cfg = dev->config;
	struct dac_audio_data *data = dev->data;
	int ret;

	ARG_UNUSED(dma_dev);
	ARG_UNUSED(channel);

	if (status < 0) {
		LOG_ERR("DMA error status=%d, stopping", status);
		LL_TIM_DisableCounter(cfg->tim);
		LL_DAC_DisableDMAReq(cfg->dac, LL_DAC_CHANNEL_1);
		LL_DAC_Disable(cfg->dac, LL_DAC_CHANNEL_1);
		data->running = false;
		data->next_valid = false;
		return;
	}

#ifdef CONFIG_DAC_AUDIO_STM32_DOUBLE_BUFFER
	/*
	 * Cyclic double-buffer mode.  DMA_STATUS_BLOCK = half-transfer (DMA
	 * has finished the first half and is now consuming the second half).
	 * DMA_STATUS_COMPLETE = full-cycle wrap (second half done, DMA wraps
	 * to the first half).  Update active_half so write() copies into the
	 * correct idle half, then notify the application.
	 */
	data->active_half = (status == DMA_STATUS_BLOCK) ? 1U : 0U;
	if (data->tx_cb != NULL) {
		data->tx_cb(dev, data->tx_cb_user_data);
	}
	return;
#endif /* CONFIG_DAC_AUDIO_STM32_DOUBLE_BUFFER */

	/*
	 * Two-pass reload to cover both the zero-gap (double-prime) and the
	 * single-prime (backward-compat) usage patterns.
	 *
	 * Pass 1 — pre-queued: buffer was staged by write() before this ISR
	 *           fired; reload immediately for minimum inter-buffer gap.
	 * Pass 2 — fallback: no pre-queue existed; the user callback fills a
	 *           buffer and calls write() which sets next_valid; reload now
	 *           so DMA restarts before the next timer tick causes DMAUDR.
	 */
	bool reloaded = false;

	if (data->next_valid) {
#if defined(CONFIG_CACHE_MANAGEMENT) && defined(CONFIG_CPU_HAS_DCACHE)
		sys_cache_data_flush_range(data->next_buf, data->next_size);
#endif
		ret = dma_reload(cfg->dma_dev, cfg->dma_channel,
				 (uint32_t)data->next_buf, data->dest_addr,
				 data->next_size);
		if (ret == 0) {
			ret = dma_start(cfg->dma_dev, cfg->dma_channel);
		}
		data->next_valid = false;
		reloaded = true;
		if (ret < 0) {
			LOG_ERR("DMA reload failed: %d, stopping", ret);
			LL_TIM_DisableCounter(cfg->tim);
			LL_DAC_DisableDMAReq(cfg->dac, LL_DAC_CHANNEL_1);
			LL_DAC_Disable(cfg->dac, LL_DAC_CHANNEL_1);
			data->running = false;
			return;
		}
	}

	if (data->tx_cb != NULL) {
		data->tx_cb(dev, data->tx_cb_user_data);
	}

	if (!reloaded && data->next_valid) {
#if defined(CONFIG_CACHE_MANAGEMENT) && defined(CONFIG_CPU_HAS_DCACHE)
		sys_cache_data_flush_range(data->next_buf, data->next_size);
#endif
		ret = dma_reload(cfg->dma_dev, cfg->dma_channel,
				 (uint32_t)data->next_buf, data->dest_addr,
				 data->next_size);
		if (ret == 0) {
			ret = dma_start(cfg->dma_dev, cfg->dma_channel);
		}
		data->next_valid = false;
		if (ret < 0) {
			LOG_ERR("DMA reload failed: %d, stopping", ret);
			LL_TIM_DisableCounter(cfg->tim);
			LL_DAC_DisableDMAReq(cfg->dac, LL_DAC_CHANNEL_1);
			LL_DAC_Disable(cfg->dac, LL_DAC_CHANNEL_1);
			data->running = false;
		}
	}
}

static void dac_audio_isr(const struct device *dev)
{
	const struct dac_audio_cfg *cfg = dev->config;
	struct dac_audio_data *data = dev->data;
	struct dma_status st;

	if (!LL_DAC_IsActiveFlag_DMAUDR1(cfg->dac)) {
		return;
	}

	LL_DAC_ClearFlag_DMAUDR1(cfg->dac);

	/*
	 * A transient underrun can occur in the single-sample window between
	 * DMA completing its last transfer and the DMA TC callback restarting
	 * it (fallback reload path in dma_tx_callback).  If DMA is already
	 * running again by the time we get here, treat it as benign.
	 */
	if (dma_get_status(cfg->dma_dev, cfg->dma_channel, &st) == 0 &&
	    st.busy) {
		return;
	}

	LOG_ERR("DAC DMA underrun on CH1 — stopping");

	LL_TIM_DisableCounter(cfg->tim);
	dma_stop(cfg->dma_dev, cfg->dma_channel);
	LL_DAC_DisableDMAReq(cfg->dac, LL_DAC_CHANNEL_1);
	LL_DAC_Disable(cfg->dac, LL_DAC_CHANNEL_1);

	data->running = false;
	data->dma_configured = false;
	data->next_valid = false;
}

static int dac_audio_configure(const struct device *dev,
				struct audio_codec_cfg *audio_cfg)
{
	const struct dac_audio_cfg *cfg = dev->config;
	struct dac_audio_data *data = dev->data;
	const struct device *clk = DEVICE_DT_GET(STM32_CLOCK_CONTROL_NODE);
	uint32_t sample_rate = (uint32_t)audio_cfg->dai_cfg.pcm.samplerate;
	uint32_t tim_clk, arr;
	int ret;

	/* Enable DAC and timer clocks */
	for (size_t i = 0; i < cfg->pclk_len; i++) {
		ret = clock_control_on(clk, (clock_control_subsys_t)&cfg->pclken[i]);
		if (ret < 0) {
			LOG_ERR("clock_control_on[%zu] failed: %d", i, ret);
			return ret;
		}
	}

	/* Get the actual timer input clock from the TIMPCLK source selector
	 * (clocks[1] of the timer node).  The clock control driver already
	 * applies the ×2 multiplier when the APB prescaler ≠ 1 and returns
	 * the AHB clock when it equals 1, so no manual factor is needed. */
	ret = clock_control_get_rate(clk,
				     (clock_control_subsys_t)&cfg->tim_clksrc,
				     &tim_clk);
	if (ret < 0) {
		LOG_ERR("clock_control_get_rate failed: %d", ret);
		return ret;
	}

	if (sample_rate == 0 || (tim_clk % sample_rate) != 0) {
		LOG_ERR("Sample rate %u Hz not exactly achievable (tim_clk=%u)",
			sample_rate, tim_clk);
		return -EINVAL;
	}
	arr = tim_clk / sample_rate - 1;

	ret = pinctrl_apply_state(cfg->pcfg, PINCTRL_STATE_DEFAULT);
	if (ret < 0) {
		LOG_ERR("pinctrl_apply_state failed: %d", ret);
		return ret;
	}

	/* Basic up-counter, update event → TRGO, period = 1/sample_rate */
	LL_TIM_SetPrescaler(cfg->tim, 0);
	LL_TIM_SetAutoReload(cfg->tim, arr);
	LL_TIM_SetTriggerOutput(cfg->tim, LL_TIM_TRGO_UPDATE);
	LL_TIM_DisableMasterSlaveMode(cfg->tim);

	/* DAC CH1: timer TRGO trigger, DMA enabled, output buffer on, GPIO connected */
	LL_DAC_SetTriggerSource(cfg->dac, LL_DAC_CHANNEL_1, cfg->trig_source);
	LL_DAC_EnableTrigger(cfg->dac, LL_DAC_CHANNEL_1);
	LL_DAC_SetOutputBuffer(cfg->dac, LL_DAC_CHANNEL_1,
			       LL_DAC_OUTPUT_BUFFER_ENABLE);
#if defined(LL_DAC_OUTPUT_MODE_NORMAL)
	/* STM32H7 and other series with extended output mode control */
	LL_DAC_SetOutputMode(cfg->dac, LL_DAC_CHANNEL_1,
			     LL_DAC_OUTPUT_MODE_NORMAL);
	LL_DAC_SetOutputConnection(cfg->dac, LL_DAC_CHANNEL_1,
				   LL_DAC_OUTPUT_CONNECT_GPIO);
#endif

	data->dest_addr = LL_DAC_DMA_GetRegAddr(cfg->dac, LL_DAC_CHANNEL_1,
						 LL_DAC_DMA_REG_DATA_12BITS_RIGHT_ALIGNED);

	memset(&data->dma_cfg, 0, sizeof(data->dma_cfg));
	data->dma_cfg.dma_slot            = cfg->dma_slot;
	data->dma_cfg.channel_direction   = MEMORY_TO_PERIPHERAL;
	data->dma_cfg.source_data_size    = 2;
	data->dma_cfg.dest_data_size      = 2;
	data->dma_cfg.source_burst_length = 1;
	data->dma_cfg.dest_burst_length   = 1;
	data->dma_cfg.complete_callback_en = 1;
	data->dma_cfg.error_callback_dis  = 0;
	data->dma_cfg.dma_callback        = dma_tx_callback;
	data->dma_cfg.user_data           = (void *)dev;
	data->dma_cfg.block_count         = 1;
	data->dma_cfg.head_block          = &data->dma_block;

	data->dma_configured = false;

	LOG_INF("configured: %u Hz, ARR=%u, tim_clk=%u Hz", sample_rate, arr, tim_clk);
	return 0;
}

static int dac_audio_write(const struct device *dev, uint8_t *buf, size_t size)
{
	const struct dac_audio_cfg *cfg = dev->config;
	struct dac_audio_data *data = dev->data;
	int ret;

#ifdef CONFIG_DAC_AUDIO_STM32_DOUBLE_BUFFER
	if (!data->dma_configured) {
		/*
		 * First write: fill both halves of the internal buffer with the
		 * same initial content so DMA plays valid data from the start
		 * even before the first half-transfer callback fires.
		 */
		data->half_bytes = size;
		memcpy(data->dbl_buf, buf, size);
		memcpy((uint8_t *)data->dbl_buf + size, buf, size);
#if defined(CONFIG_CACHE_MANAGEMENT) && defined(CONFIG_CPU_HAS_DCACHE)
		sys_cache_data_flush_range(data->dbl_buf, 2U * size);
#endif
		memset(&data->dma_block, 0, sizeof(data->dma_block));
		data->dma_block.source_address   = (uint32_t)data->dbl_buf;
		data->dma_block.dest_address     = data->dest_addr;
		data->dma_block.block_size       = 2U * size;
		data->dma_block.source_addr_adj  = DMA_ADDR_ADJ_INCREMENT;
		data->dma_block.dest_addr_adj    = DMA_ADDR_ADJ_NO_CHANGE;
		data->dma_block.source_reload_en = 1; /* cyclic: wrap at end */

		ret = dma_config(cfg->dma_dev, cfg->dma_channel, &data->dma_cfg);
		if (ret < 0) {
			LOG_ERR("dma_config failed: %d", ret);
			return ret;
		}
		ret = dma_start(cfg->dma_dev, cfg->dma_channel);
		if (ret < 0) {
			LOG_ERR("dma_start failed: %d", ret);
			return ret;
		}
		data->dma_configured = true;
		data->active_half    = 0;
	} else {
		/*
		 * Subsequent writes: copy into the idle half while DMA plays
		 * the active half.  The cache flush covers only the half being
		 * written, not the half currently under DMA.
		 */
		uint8_t idle = 1U - data->active_half;
		void   *dst  = (uint8_t *)data->dbl_buf + (size_t)idle * data->half_bytes;

		memcpy(dst, buf, data->half_bytes);
#if defined(CONFIG_CACHE_MANAGEMENT) && defined(CONFIG_CPU_HAS_DCACHE)
		sys_cache_data_flush_range(dst, data->half_bytes);
#endif
	}
	return 0;
#endif /* CONFIG_DAC_AUDIO_STM32_DOUBLE_BUFFER */

	if (!data->dma_configured) {
		/*
		 * First call (prime): configure and start DMA now.  Cache flush
		 * happens here because the DMA will read this buffer directly.
		 */
#if defined(CONFIG_CACHE_MANAGEMENT) && defined(CONFIG_CPU_HAS_DCACHE)
		sys_cache_data_flush_range(buf, size);
#endif
		memset(&data->dma_block, 0, sizeof(data->dma_block));
		data->dma_block.source_address  = (uint32_t)buf;
		data->dma_block.dest_address    = data->dest_addr;
		data->dma_block.block_size      = size;
		data->dma_block.source_addr_adj = DMA_ADDR_ADJ_INCREMENT;
		data->dma_block.dest_addr_adj   = DMA_ADDR_ADJ_NO_CHANGE;

		ret = dma_config(cfg->dma_dev, cfg->dma_channel, &data->dma_cfg);
		if (ret < 0) {
			LOG_ERR("dma_config failed: %d", ret);
			return ret;
		}
		ret = dma_start(cfg->dma_dev, cfg->dma_channel);
		if (ret < 0) {
			LOG_ERR("dma_start failed: %d", ret);
			return ret;
		}
		data->dma_configured = true;
	} else {
		/*
		 * DMA already running: pre-queue the buffer so dma_tx_callback()
		 * can reload at ISR time before invoking the user callback.
		 * Cache flush is deferred to the callback to keep write() fast.
		 */
		data->next_buf   = buf;
		data->next_size  = size;
		data->next_valid = true;
	}
	return 0;
}

static int dac_audio_start(const struct device *dev, audio_dai_dir_t dir)
{
	const struct dac_audio_cfg *cfg = dev->config;
	struct dac_audio_data *data = dev->data;

	if ((dir & AUDIO_DAI_DIR_TX) == 0) {
		return -ENOTSUP;
	}

	LL_DAC_Enable(cfg->dac, LL_DAC_CHANNEL_1);
	k_busy_wait(10);

	LL_DAC_ClearFlag_DMAUDR1(cfg->dac);
	LL_DAC_EnableIT_DMAUDR1(cfg->dac);
	LL_DAC_EnableDMAReq(cfg->dac, LL_DAC_CHANNEL_1);
	LL_TIM_EnableCounter(cfg->tim);

	data->running = true;
	LOG_INF("TX started");
	return 0;
}

static int dac_audio_stop(const struct device *dev, audio_dai_dir_t dir)
{
	const struct dac_audio_cfg *cfg = dev->config;
	struct dac_audio_data *data = dev->data;

	if ((dir & AUDIO_DAI_DIR_TX) == 0) {
		return -ENOTSUP;
	}

	LL_TIM_DisableCounter(cfg->tim);
	LL_DAC_DisableIT_DMAUDR1(cfg->dac);
	dma_stop(cfg->dma_dev, cfg->dma_channel);
	LL_DAC_DisableDMAReq(cfg->dac, LL_DAC_CHANNEL_1);
	LL_DAC_Disable(cfg->dac, LL_DAC_CHANNEL_1);

	data->running = false;
	data->dma_configured = false;
	data->next_valid = false;
#ifdef CONFIG_DAC_AUDIO_STM32_DOUBLE_BUFFER
	data->active_half = 0;
#endif

	LOG_INF("TX stopped");
	return 0;
}

static void dac_audio_start_output(const struct device *dev)
{
	dac_audio_start(dev, AUDIO_DAI_DIR_TX);
}

static void dac_audio_stop_output(const struct device *dev)
{
	dac_audio_stop(dev, AUDIO_DAI_DIR_TX);
}

static int dac_audio_set_property(const struct device *dev,
				   audio_property_t property,
				   audio_channel_t channel,
				   audio_property_value_t val)
{
	ARG_UNUSED(dev);
	ARG_UNUSED(property);
	ARG_UNUSED(channel);
	ARG_UNUSED(val);
	return -ENOTSUP;
}

static int dac_audio_apply_properties(const struct device *dev)
{
	ARG_UNUSED(dev);
	return 0;
}

static int dac_audio_register_done_callback(const struct device *dev,
					     audio_codec_tx_done_callback_t tx_cb,
					     void *tx_user_data,
					     audio_codec_rx_done_callback_t rx_cb,
					     void *rx_user_data)
{
	struct dac_audio_data *data = dev->data;

	ARG_UNUSED(rx_cb);
	ARG_UNUSED(rx_user_data);

	data->tx_cb           = tx_cb;
	data->tx_cb_user_data = tx_user_data;
	return 0;
}

static const struct audio_codec_api dac_audio_codec_api = {
	.configure              = dac_audio_configure,
	.start_output           = dac_audio_start_output,
	.stop_output            = dac_audio_stop_output,
	.set_property           = dac_audio_set_property,
	.apply_properties       = dac_audio_apply_properties,
	.start                  = dac_audio_start,
	.stop                   = dac_audio_stop,
	.write                  = dac_audio_write,
	.register_done_callback = dac_audio_register_done_callback,
};

static int dac_audio_init(const struct device *dev)
{
	const struct dac_audio_cfg *cfg = dev->config;

	if (!device_is_ready(cfg->dma_dev)) {
		LOG_ERR("DMA device not ready");
		return -ENODEV;
	}

	cfg->irq_config();

	return 0;
}

/*
 * pclken[0]: DAC clock    — clocks[0] of the parent dac node
 * pclken[1]: timer enable — clocks[0] of the st,timer node
 * tim_clksrc:               clocks[1] of the st,timer node (TIMPCLK source
 *                           selector); used only with clock_control_get_rate(),
 *                           NOT with clock_control_on().  The clock driver
 *                           applies the ×2 rule internally, so no manual
 *                           factor is needed in the driver.
 */
/*
 * The DAC DMA underrun interrupt is on the same IRQ line as TIM6 (e.g.
 * TIM6_DAC_IRQn on STM32F7).  The line is taken from the timer node's
 * interrupts property because the plain st,stm32-dac binding has none.
 */
#define DAC_AUDIO_INIT(index)							\
	PINCTRL_DT_INST_DEFINE(index);						\
										\
	static void dac_audio_irq_config_##index(void)				\
	{									\
		IRQ_CONNECT(DT_IRQ_BY_IDX(					\
				DT_INST_PHANDLE(index, st_timer), 0, irq),	\
			    DT_IRQ_BY_IDX(					\
				DT_INST_PHANDLE(index, st_timer), 0, priority),	\
			    dac_audio_isr,					\
			    DEVICE_DT_INST_GET(index), 0);			\
		irq_enable(DT_IRQ_BY_IDX(					\
				DT_INST_PHANDLE(index, st_timer), 0, irq));	\
	}									\
										\
	static const struct stm32_pclken pclken_##index[] = {			\
		{								\
			.bus = DT_CLOCKS_CELL_BY_IDX(				\
				DT_PARENT(DT_DRV_INST(index)), 0, bus),		\
			.enr = DT_CLOCKS_CELL_BY_IDX(				\
				DT_PARENT(DT_DRV_INST(index)), 0, bits),	\
		},								\
		{								\
			.bus = DT_CLOCKS_CELL_BY_IDX(				\
				DT_INST_PHANDLE(index, st_timer), 0, bus),	\
			.enr = DT_CLOCKS_CELL_BY_IDX(				\
				DT_INST_PHANDLE(index, st_timer), 0, bits),	\
		},								\
	};									\
										\
	static struct dac_audio_data dac_audio_data_##index;			\
										\
	static const struct dac_audio_cfg dac_audio_cfg_##index = {		\
		.dac         = (DAC_TypeDef *)					\
				DT_REG_ADDR(DT_PARENT(DT_DRV_INST(index))),	\
		.tim         = (TIM_TypeDef *)					\
				DT_REG_ADDR(DT_INST_PHANDLE(index, st_timer)),	\
		.trig_source = STM32_DAC_TRIG_SOURCE(index),			\
		.dma_dev     = DEVICE_DT_GET(STM32_DMA_CTLR(index, tx)),	\
		.dma_channel = DT_INST_DMAS_CELL_BY_NAME(index, tx, channel),	\
		.dma_slot    = STM32_DMA_SLOT(index, tx, slot),			\
		.pcfg        = PINCTRL_DT_INST_DEV_CONFIG_GET(index),		\
		.pclken      = pclken_##index,					\
		.pclk_len    = 2,						\
		.tim_clksrc  = {						\
			.bus = DT_CLOCKS_CELL_BY_IDX(				\
				DT_INST_PHANDLE(index, st_timer), 1, bus),	\
			.enr = DT_CLOCKS_CELL_BY_IDX(				\
				DT_INST_PHANDLE(index, st_timer), 1, bits),	\
		},								\
		.irq_config  = dac_audio_irq_config_##index,			\
	};									\
										\
	DEVICE_DT_INST_DEFINE(index, dac_audio_init, NULL,			\
			      &dac_audio_data_##index,				\
			      &dac_audio_cfg_##index,				\
			      POST_KERNEL,					\
			      CONFIG_AUDIO_CODEC_INIT_PRIORITY,			\
			      &dac_audio_codec_api);

DT_INST_FOREACH_STATUS_OKAY(DAC_AUDIO_INIT)
